scripts: fix attribute error if no subcommand was provided
Because `args.rw` value is being checked first, when user doesn't choose
one of the required subcommands (etherbone or bist), `AttributeError`
happens.

```
Traceback (most recent call last):
  File
"/path/to/the/project/rowhammer-tester/rowhammer_tester/scripts/benchmark.py",
line 95, in <module>
    if args.rw == 'write':
AttributeError: 'Namespace' object has no attribute 'rw'
```

Quick fix is to swap the order of checks.

Signed-off-by: Michal Sieron <msieron@antmicro.com>